version: "3.9"
services:
    db:
        container_name: db
        image: mongo
        restart: unless-stopped
        ports:
            - '27017:27017'
        networks: 
            - app-network

    games-app:
        container_name: games
        image: nathan/games-graphql
        restart: unless-stopped
        build: .
        env_file: .env
        environment: 
            - MONGO_HOSTNAME=db
            - MONGO_PORT=$MONGO_PORT
            - MONGO_DB=$MONGO_DB
        ports:
            - '10000:10000'
        networks: 
            - app-network
        depends_on: 
            - mongo

networks: 
    app-network:
        driver: bridge
        
