version: "3.9"
services:
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
        restart: always
        networks: 
            - first_network

    games-app:
        container_name: games
        image: nathan/games-graphql
        #network_mode: host
        restart: always
        build: .
        ports:
            - '10000:10000'
        networks: 
            - first_network

networks: 
    first_network:
        driver: bridge
        
